### ISSUE TITLE
is this no longer mainained?

### ISSUE THREAD

**Issue by Sasiko** [casKd-dev/yagpdb#3]
docker images is several versions behind yagpdb so was wondering if this is dead now?

**Comment by Gibby** [comment]
@maidos I got the latest built over at https://hub.docker.com/r/gibby/yagpdb

**Comment by casKd-dev** [comment]
> docker images is several versions behind yagpdb so was wondering if this is dead now?

I have abandoned the support for docker a long time ago since i have deleted my discord account. Someone should've taken that over afaik. You are free to fork this repository and do your own changes though.
